language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -r requirements_tests.txt
# command to run tests
script:
  - nosetests ./tests --with-coverage --cover-package=atservices --cover-xml
after_success:
  - coverage combine
  - coveralls